@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.4.0
rem  Generated on: 2026-07-07 14:47
rem
rem  Ship ONLY this file in your repo.  On first run it:
rem    1. Checks Python
rem    2. Creates / verifies the virtual environment
rem    3. Installs dependencies
rem    4. Writes companion scripts beside this file:
rem       run.bat  pip.bat  shell.bat  sync.bat  doctor.bat
rem
rem  Companion scripts are NOT overwritten if they already exist.
rem  Add them to .gitignore to keep your repo tidy.
rem ============================================================

set "PROJECT_NAME=Webbrowser"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setup: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Environment check + venv bootstrap ───────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 ( echo [ERROR] venv creation failed. & pause & exit /b 1 )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Run sync.bat after adding dependencies.
        echo.
    )
)

rem ── 2. Write companion scripts ───────────────────────────────
echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ─────────────────────────────────────────────────
set "OUTFILE=run.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_run_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbCBFbmFibGVEZWxheWVkRXhwYW5zaW9uDQpjZCAvZCAiJX5kcDAi
        echo DQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCBSdW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYg
        echo QmF0Y2ggVGVtcGxhdGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0K
        echo cmVtICBHZW5lcmF0ZWQgb246IDIwMjYtMDctMDcgMTQ6NDcNCnJlbQ0KcmVtICBFTlRSWV9NT0RF
        echo Og0KcmVtICAgIGZpbGUgICAtPiBweXRob24gYXBwLnB5DQpyZW0gICAgbW9kdWxlIC0+IHB5dGhv
        echo biAtbSBwYWNrYWdlLm1vZHVsZQ0KcmVtICAgIHJ1bm5lciAtPiBweXRob24gLW0gcnVubmVyX21v
        echo ZHVsZSBbYXJncy4uLl0NCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNUX05BTUU9V2ViYnJvd3NlciIN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIkVOVFJZX01PREU9ZmlsZSINCnNldCAiQVBQX0VO
        echo VFJZPXNyY1xtYWluLnB5Ig0Kc2V0ICJSVU5ORVJfQVJHUz0iDQoNCnNldCAiUFk9JUNEJVwlVkVO
        echo Vl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4ZSINCg0KaWYgbm90IGV4aXN0ICIlUFklIiAoDQogICAg
        echo ZWNobyBbRVJST1JdIExvY2FsIHZlbnYgbm90IGZvdW5kOiAiJVBZJSINCiAgICBlY2hvLg0KICAg
        echo IGVjaG8gRml4IHdpdGg6DQogICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9ESVIlIg0K
        echo ICAgIGVjaG8gICAiJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUiIC1tIHBpcCBpbnN0YWxs
        echo IC0tdXBncmFkZSBwaXANCiAgICBlY2hvICAgIiVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhl
        echo IiAtbSBwaXAgaW5zdGFsbCAtciByZXF1aXJlbWVudHMudHh0DQogICAgZWNoby4NCiAgICBwYXVz
        echo ZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQppZiAvSSAiJUVOVFJZX01PREUlIj09ImZpbGUiIGlmIG5v
        echo dCBleGlzdCAiJUFQUF9FTlRSWSUiICgNCiAgICBlY2hvIFtFUlJPUl0gRW50cnkgZmlsZSBub3Qg
        echo Zm91bmQ6ICIlQVBQX0VOVFJZJSINCiAgICBlY2hvIEVkaXQgcnVuLmJhdCBvciBydW4gd2l0aCB0
        echo aGUgY29ycmVjdCBlbnRyeSBmaWxlLg0KICAgIHBhdXNlDQogICAgZXhpdCAvYiAxDQopDQoNCnRp
        echo dGxlICIlUFJPSkVDVF9OQU1FJSAtIFJVTiINCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBSdW5uaW5nIDogJVBS
        echo T0pFQ1RfTkFNRSUNCmVjaG8gIFByb2plY3QgOiAlQ0QlDQplY2hvICBQeXRob24gIDogJVBZJQ0K
        echo ZWNobyAgTW9kZSAgICA6ICVFTlRSWV9NT0RFJQ0KZWNobyAgRW50cnkgICA6ICVBUFBfRU5UUlkl
        echo DQppZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgZWNobyAgQXJncyAgICA6ICVSVU5ORVJf
        echo QVJHUyUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09DQplY2hvLg0KDQpzZXQgIkVYSVRDT0RFPTAiDQoNCmlmIC9JICIlRU5U
        echo UllfTU9ERSUiPT0ibW9kdWxlIiAoDQogICAgIiVQWSUiIC1tICVBUFBfRU5UUlklICUqDQopIGVs
        echo c2UgaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJydW5uZXIiICgNCiAgICBpZiBkZWZpbmVkIFJVTk5F
        echo Ul9BUkdTICgNCiAgICAgICAgIiVQWSUiIC1tICVBUFBfRU5UUlklICFSVU5ORVJfQVJHUyEgJSoN
        echo CiAgICApIGVsc2UgKA0KICAgICAgICAiJVBZJSIgLW0gJUFQUF9FTlRSWSUgJSoNCiAgICApDQop
        echo IGVsc2UgKA0KICAgICIlUFklIiAiJUFQUF9FTlRSWSUiICUqDQopDQoNCnNldCAiRVhJVENPREU9
        echo IUVSUk9STEVWRUwhIg0KDQplY2hvLg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFByb2Nlc3MgZXhpdGVkIHdp
        echo dGggY29kZTogIUVYSVRDT0RFIQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnBhdXNlDQpleGl0IC9iICFFWElUQ09ERSEN
        echo Cg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── pip.bat ─────────────────────────────────────────────────
set "OUTFILE=pip.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_pip_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QtbG9jYWwgcGlwIHdyYXBwZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxh
        echo dGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0
        echo ZWQgb246IDIwMjYtMDctMDcgMTQ6NDcNCnJlbQ0KcmVtICBVc2FnZToNCnJlbSAgICBwaXAuYmF0
        echo IGluc3RhbGwgcmVxdWVzdHMNCnJlbSAgICBwaXAuYmF0IGluc3RhbGwgLXIgcmVxdWlyZW1lbnRz
        echo LnR4dA0KcmVtICAgIHBpcC5iYXQgZnJlZXplID4gcmVxdWlyZW1lbnRzLnR4dA0KcmVtICAgIHBp
        echo cC5iYXQgbGlzdA0KcmVtICAgIHBpcC5iYXQgdW5pbnN0YWxsIHJlcXVlc3RzDQpyZW0gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQoN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5
        echo dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2Nh
        echo bCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
        echo DQoiJVBZJSIgLW0gcGlwICUqDQpleGl0IC9iICVFUlJPUkxFVkVMJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── shell.bat ─────────────────────────────────────────────────
set "OUTFILE=shell.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_shell_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpjZCAvZCAiJX5kcDAiDQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCB2ZW52IHNo
        echo ZWxsDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRvciAoTGVv
        echo biBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2LTA3LTA3
        echo IDE0OjQ3DQpyZW0NCnJlbSAgT3BlbnMgYW4gYWN0aXZhdGVkIENNRCBzZXNzaW9uIGZvciB0aGlz
        echo IHByb2plY3QuDQpyZW0gIFVzZSBvbmx5IHdoZW4geW91IG5lZWQgYW4gaW50ZXJhY3RpdmUgdmVu
        echo diBzZXNzaW9uLg0KcmVtICBFeGl0IHdpdGg6IGV4aXQNCnJlbSA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNU
        echo X05BTUU9V2ViYnJvd3NlciINCnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIkFDVElWQVRFPSVD
        echo RCVcJVZFTlZfRElSJVxTY3JpcHRzXGFjdGl2YXRlLmJhdCINCg0KaWYgbm90IGV4aXN0ICIlQUNU
        echo SVZBVEUlIiAoDQogICAgZWNobyBbRVJST1JdIExvY2FsIHZlbnYgd2FzIG5vdCBmb3VuZDoNCiAg
        echo ICBlY2hvICAgICAgICAgIiVBQ1RJVkFURSUiDQogICAgZWNoby4NCiAgICBlY2hvIENyZWF0ZSBp
        echo dCB3aXRoOg0KICAgIGVjaG8gICAgICAgICBweXRob24gLW0gdmVudiAiJVZFTlZfRElSJSINCiAg
        echo ICBlY2hvLg0KICAgIHBhdXNlDQogICAgZXhpdCAvYiAxDQopDQoNCnRpdGxlICIlUFJPSkVDVF9O
        echo QU1FJSAtIFZFTlYgU0hFTEwiDQpjYWxsICIlQUNUSVZBVEUlIg0KDQplY2hvID09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAg
        echo UHJvamVjdCBzaGVsbCBhY3RpdmF0ZWQNCmVjaG8gIFByb2plY3Q6ICIlQ0QlIg0KZWNobyAgUHl0
        echo aG9uIDoNCndoZXJlIHB5dGhvbg0KZWNobyAgVHlwZSAiZXhpdCIgdG8gbGVhdmUgdGhpcyBzaGVs
        echo bC4NCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09DQplY2hvLg0KY21kIC9rDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── sync.bat ─────────────────────────────────────────────────
set "OUTFILE=sync.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_sync_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIERlcGVu
        echo ZGVuY3kgU3luYyAocGlwKQ0KcmVtICBHZW5lcmF0ZWQgYnkgVmVudiBCYXRjaCBUZW1wbGF0ZSBH
        echo ZW5lcmF0b3IgKExlb24gUHJpZXN0IC8gN2gzdjAxZCkgdjMuNC4wDQpyZW0gIEdlbmVyYXRlZCBv
        echo bjogMjAyNi0wNy0wNyAxNDo0Nw0KcmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1XZWJicm93
        echo c2VyIg0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiUFk9JUNEJVwlVkVOVl9ESVIlXFNjcmlw
        echo dHNccHl0aG9uLmV4ZSINCg0KaWYgbm90IGV4aXN0ICIlUFklIiAoDQogICAgZWNobyBbRVJST1Jd
        echo IExvY2FsIHZlbnYgbm90IGZvdW5kOiAiJVBZJSINCiAgICBlY2hvLg0KICAgIGVjaG8gQ3JlYXRl
        echo IGl0IHdpdGg6DQogICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9ESVIlIg0KICAgIHBh
        echo dXNlDQogICAgZXhpdCAvYiAxDQopDQoNCnRpdGxlICIlUFJPSkVDVF9OQU1FJSAtIFNZTkMiDQoN
        echo CmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09DQplY2hvICBTeW5jaW5nOiAlUFJPSkVDVF9OQU1FJQ0KZWNobyAgUHl0aG9uIDog
        echo JVBZJQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT0NCmVjaG8uDQoNCmVjaG8gWzEvM10gVXBncmFkaW5nIHBpcC4uLg0KZWNo
        echo byA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT0NCiIlUFklIiAtbSBwaXAgaW5zdGFsbCAtLXVwZ3JhZGUgcGlwDQplY2hvLg0KDQppZiBl
        echo eGlzdCAicmVxdWlyZW1lbnRzLnR4dCIgKA0KICAgIGVjaG8gWzIvM10gSW5zdGFsbGluZyBmcm9t
        echo IHJlcXVpcmVtZW50cy50eHQuLi4NCiAgICBlY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KICAgICIlUFklIiAtbSBwaXAgaW5z
        echo dGFsbCAtciByZXF1aXJlbWVudHMudHh0DQogICAgZWNoby4NCikgZWxzZSAoDQogICAgZWNobyBb
        echo Mi8zXSBTS0lQUEVEOiBObyByZXF1aXJlbWVudHMudHh0IGZvdW5kLg0KICAgIGVjaG8gICAgICAg
        echo Q3JlYXRlIG9uZSB3aXRoOiBwaXAuYmF0IGZyZWV6ZSBePiByZXF1aXJlbWVudHMudHh0DQogICAg
        echo ZWNoby4NCikNCg0KZWNobyBbMy8zXSBEZXBlbmRlbmN5IGhlYWx0aCBjaGVjay4uLg0KZWNobyA9
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT0NCiIlUFklIiAtbSBwaXAgY2hlY2sNCmVjaG8uDQoNCmVjaG8gPT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBTWU5DIENP
        echo TVBMRVRFDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4aXQgL2IgMA0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── doctor.bat ─────────────────────────────────────────────────
set "OUTFILE=doctor.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_doctor_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgRG9jdG9yDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA3LTA3IDE0OjQ3DQpyZW0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQoNCnNldCAiUFJPSkVDVF9OQU1FPVdlYmJyb3dzZXIiDQpz
        echo ZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJFTlRSWV9NT0RFPWZpbGUiDQpzZXQgIkFQUF9FTlRS
        echo WT1zcmNcbWFpbi5weSINCnNldCAiUlVOTkVSX0FSR1M9Ig0Kc2V0ICJQWT0lQ0QlXCVWRU5WX0RJ
        echo UiVcU2NyaXB0c1xweXRob24uZXhlIg0KDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgUFJPSkVDVCBET0NUT1I6
        echo ICVQUk9KRUNUX05BTUUlDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgUHJvamVjdCA6ICVDRCUNCmVjaG8gIE1v
        echo ZGUgICAgOiAlRU5UUllfTU9ERSUNCmVjaG8gIEVudHJ5ICAgOiAlQVBQX0VOVFJZJQ0KaWYgL0kg
        echo IiVFTlRSWV9NT0RFJSI9PSJydW5uZXIiIGVjaG8gIEFyZ3MgICAgOiAlUlVOTkVSX0FSR1MlDQpl
        echo Y2hvLg0KDQppZiBub3QgZXhpc3QgIiVQWSUiICgNCiAgICBlY2hvIFtGQUlMXSB2ZW52IG5vdCBm
        echo b3VuZCBhdDogIiVQWSUiDQogICAgZWNoby4NCiAgICBlY2hvIENyZWF0ZSBpdCB3aXRoOg0KICAg
        echo IGVjaG8gICBweXRob24gLW0gdmVudiAiJVZFTlZfRElSJSINCiAgICBwYXVzZQ0KICAgIGV4aXQg
        echo L2IgMQ0KKQ0KDQplY2hvIFtPS10gdmVudiBmb3VuZDogIiVQWSUiDQplY2hvLg0KDQplY2hvIC0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LQ0KZWNobyAgUHl0aG9uIEVudmlyb25tZW50DQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KIiVQWSUiIC1jICJpbXBvcnQg
        echo c3lzOyBwcmludCgnRXhlY3V0YWJsZSA6Jywgc3lzLmV4ZWN1dGFibGUpOyBwcmludCgnVmVyc2lv
        echo biAgICA6Jywgc3lzLnZlcnNpb24uc3BsaXQoKVswXSk7IHByaW50KCdQcmVmaXggICAgIDonLCBz
        echo eXMucHJlZml4KSINCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBwaXAgdmVyc2lvbg0KZWNobyAt
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0NCiIlUFklIiAtbSBwaXAgLS12ZXJzaW9uDQplY2hvLg0KDQplY2hvIC0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAgSW5z
        echo dGFsbGVkIFBhY2thZ2VzDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KIiVQWSUiIC1tIHBpcCBsaXN0DQplY2hvLg0KDQpl
        echo Y2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLQ0KZWNobyAgRGVwZW5kZW5jeSBIZWFsdGgNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIgLW0gcGlw
        echo IGNoZWNrDQplY2hvLg0KDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAgRW50cnkgUG9pbnQgQ2hlY2sNCmVjaG8g
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tDQppZiAvSSAiJUVOVFJZX01PREUlIj09ImZpbGUiICgNCiAgICBpZiBleGlzdCAiJUFQUF9F
        echo TlRSWSUiICgNCiAgICAgICAgZWNobyBbT0tdIEVudHJ5IGZpbGUgZm91bmQ6ICIlQVBQX0VOVFJZ
        echo JSINCiAgICApIGVsc2UgKA0KICAgICAgICBlY2hvIFtGQUlMXSBFbnRyeSBmaWxlIE5PVCBmb3Vu
        echo ZDogIiVBUFBfRU5UUlklIg0KICAgICkNCikgZWxzZSAoDQogICAgIiVQWSUiIC1jICJpbXBvcnQg
        echo aW1wb3J0bGliLnV0aWwsIHN5czsgbmFtZT1yJyVBUFBfRU5UUlklJzsgc3BlYz1pbXBvcnRsaWIu
        echo dXRpbC5maW5kX3NwZWMobmFtZSk7IHByaW50KCgnW09LXSBNb2R1bGUgZm91bmQ6ICcgaWYgc3Bl
        echo YyBlbHNlICdbRkFJTF0gTW9kdWxlIE5PVCBmb3VuZDogJykgKyBuYW1lKTsgc3lzLmV4aXQoMCBp
        echo ZiBzcGVjIGVsc2UgMSkiIDI+bnVsDQogICAgaWYgZXJyb3JsZXZlbCAxIGVjaG8gW0ZBSUxdIE1v
        echo ZHVsZSBpbXBvcnQgdGVzdCBmYWlsZWQuDQogICAgaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJydW5u
        echo ZXIiIGVjaG8gW0lORk9dIFJ1bm5lciBhcmdzOiAiJVJVTk5FUl9BUkdTJSINCikNCmVjaG8uDQoN
        echo CmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tDQplY2hvICBQcm9qZWN0IEZpbGVzDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KaWYgZXhpc3QgInV2Lmxv
        echo Y2siICAgICAgICAgIGVjaG8gW09LXSAgIHV2LmxvY2sgZm91bmQNCmlmIGV4aXN0ICJweXByb2pl
        echo Y3QudG9tbCIgICBlY2hvIFtPS10gICBweXByb2plY3QudG9tbCBmb3VuZA0KaWYgZXhpc3QgInJl
        echo cXVpcmVtZW50cy50eHQiIGVjaG8gW09LXSAgIHJlcXVpcmVtZW50cy50eHQgZm91bmQNCmlmIG5v
        echo dCBleGlzdCAicmVxdWlyZW1lbnRzLnR4dCIgZWNobyBbV0FSTl0gcmVxdWlyZW1lbnRzLnR4dCBt
        echo aXNzaW5nDQplY2hvLg0KDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAgUHlRdDYgV2ViRW5naW5lIENoZWNrDQpl
        echo Y2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLQ0KIiVQWSUiIC1jICJmcm9tIFB5UXQ2IGltcG9ydCBRdENvcmU7IHByaW50KCdQeVF0
        echo OicsIFF0Q29yZS5QWVFUX1ZFUlNJT05fU1RSKTsgcHJpbnQoJ1F0ICA6JywgUXRDb3JlLlFUX1ZF
        echo UlNJT05fU1RSKTsgZnJvbSBQeVF0Ni5RdFdlYkVuZ2luZVdpZGdldHMgaW1wb3J0IFFXZWJFbmdp
        echo bmVWaWV3OyBwcmludCgnW09LXSBXZWJFbmdpbmUgaW1wb3J0ZWQgc3VjY2Vzc2Z1bGx5LicpIiAy
        echo PiYxDQppZiBlcnJvcmxldmVsIDEgKA0KICAgIGVjaG8gW0ZBSUxdIFB5UXQ2IFdlYkVuZ2luZSBj
        echo aGVjayBmYWlsZWQuDQogICAgZWNobyAgICAgICAgUnVuIG1hbnVhbGx5IGZvciBmdWxsIHRyYWNl
        echo YmFjazoNCiAgICBlY2hvICAgICAgICAiJVBZJSIgLWMgImZyb20gUHlRdDYuUXRXZWJFbmdpbmVX
        echo aWRnZXRzIGltcG9ydCBRV2ViRW5naW5lVmlldyINCikgZWxzZSAoDQogICAgZWNobyBbT0tdIFB5
        echo UXQ2IFdlYkVuZ2luZSBpcyBhdmFpbGFibGUuDQopDQplY2hvLg0KDQplY2hvID09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAg
        echo RE9DVE9SIENPTVBMRVRFDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4aXQgL2IgMA0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts written (existing files were NOT overwritten).
echo  Add them to .gitignore to keep your repo tidy.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
rem (test.bat not included)
echo ============================================================
pause
exit /b 0
